name: elasticsearch_kibana
services:
  elasticsearch:
    image: elasticsearch:8.5.1
    restart: always
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - http.cors.enabled=true
    - http.cors.allow-origin="https://app.elasticvue.com"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:8.5.1
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data: