services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672 #web UI - login: guest:guest
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq

networks:
  rabbitmq:
    driver: bridge