services:
  prometheus:
    image: prom/prometheus
    restart: always
    #http://host.docker.internal:9090
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml:ro
    networks:
      - monitoring

  grafana: 
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  monitoring: